### ISSUE TITLE
lftp-mirror-action uploads all files every time it runs despite setting "onlyNewer: true"

### ISSUE THREAD

**Issue by ghost** [pressidium/lftp-mirror-action#5] opened 2024-01-20 12:59 UTC
Hi everyone,

I read the section https://github.com/pressidium/lftp-mirror-action#restoring-modification-times, but I'm not sure I understand it correctly. Since I still encounter the issue that all my files are being uploaded every time, even after adding "onlyNewer: true". I'm also not sure if I need to add "fetch-depth: 0" and if this is connected to the issue. It added it and still same issue with uploading all files instead of only newer files.

Please see my ```main.yaml``` below. Do you have any suggstions what I am missing?

```
on: push
name: Publish to IONOS
jobs:
  web-deploy:
    name: HN MVP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        # lftp settings
        onlyNewer: true
        # Mirror command options
        localDir: '.'
        remoteDir: './HN'
        reverse: true
```

Thank you in advance!

**Comment by over-engineer** [comment] 2024-01-20 19:07
Hey, @HyveNow!

>I'm also not sure if I need to add "fetch-depth: 0"

Yes, setting `fetch-depth` to `0` is required in order to fetch the entire Git history, and restore the modification time of the files based on the date of the most recent commit that modified them (as described in the [Restoring modification times](https://github.com/pressidium/lftp-mirror-action#restoring-modification-times) section that you mentioned).

The GitHub Actions workflow you provided (assuming `fetch-depth` was also set to `0`) seems to be correct.

```yaml
- name: Get latest code
  uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

>same issue with uploading all files instead of only newer files.

I just ran it on another GitHub repository with that configuration and I couldn’t reproduce the issue (only modified files with a newer timestamp were transferred), so there’s probably something else we’re missing :thinking:

Is this the entire `main.yaml`? Are there any additional steps in the `web-deploy` job, or any other jobs defined in the workflow?

**Comment by ghost** [comment] 2024-01-20 19:24
Hey @over-engineer , thank for the quick reply! 

Yes, that is the entire `main.yaml`. Now added back the `fetch-depth: 0`. Please see below.

Any command I should try to run? Like [git-restore-mtime-action](https://github.com/chetan/git-restore-mtime-action) ? Did not fully understand if this would help.

`main.yaml`:
```
on: push
name: Publish to IONOS
jobs:
  web-deploy:
    name: HN MVP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Sync files
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        # lftp settings
        onlyNewer: true
        # Mirror command options
        localDir: '.'
        remoteDir: './HN'
        reverse: true
```

Thanks and best!

**Comment by over-engineer** [comment] 2024-01-20 20:07
@HyveNow Could you please share the output of your `web-deploy` job for the latest workflow run?

Here’s how to do that:

1. Navigate to your GitHub repository
2. Click on “Actions”
3. Select the latest workflow run
4. Select the `web-deploy` job
5. A panel containing the logs of your job will be shown. Click on the _cog_ icon, which is located at the top-right corner of that panel
6. Click on “Download log archive”
7. Upload that archive here

I think that GitHub secrets are automatically censored. However, **please double-check the log archive to ensure there’s no sensitive information, like FTP credentials, exposed before sharing it.**

---

A few screenshots to help you locate the “Download log archive” option:

![screenshot-1](https://github.com/pressidium/lftp-mirror-action/assets/6157348/b56ba7c2-83ec-475f-abac-915b05ded992)

![screenshot-2](https://github.com/pressidium/lftp-mirror-action/assets/6157348/b96a50f0-f03a-45b4-8b56-28ba4941ee8c)

![screenshot-3](https://github.com/pressidium/lftp-mirror-action/assets/6157348/ff119daa-5780-4101-9a3b-3404c06127ad)

![screenshot-4](https://github.com/pressidium/lftp-mirror-action/assets/6157348/d4efffc0-e16e-4d03-b646-b9f8a11e9d28)

**Comment by ghost** [comment] 2024-01-21 11:43
Hi @over-engineer I think I solved it. I deployed to a new `remoteDir` and now the deployment is done in 10-15 minutes instead of 1-2 hours before. 

If I run into the same issue again I will post the logs and we can take it form there.

Thank you!

**Comment by over-engineer** [comment] 2024-01-21 14:16
@HyveNow Hello! I’m glad you were able to find a solution. I’ll go ahead and close this as resolved. Feel free to reopen it if the issue resurfaces.

Have a good one!

**Closed as completed by over-engineer** 2024-01-21 14:16 UTC
